Repository hacf-fr/hassRenaultZE, pull requests merged in 2020-12, with the labels that each got.

#86 Add unit for Charging Remaining Time sensor
  custom_components/renault/sensor.py
Labels: enhancement

#88 Bump renault_api from 0.0.2 to 0.0.3
  custom_components/renault/manifest.json
Labels: dependencies

#89 Implement release-drafter
  .github/release-drafter.yml
  .github/workflows/release.yml
Labels: ci

#96 Add translations for charge-mode
  custom_components/renault/const.py
  custom_components/renault/sensor.py
  custom_components/renault/translations/sensor.en.json
  custom_components/renault/translations/sensor.fr.json
Labels: enhancement
