Repository hacf-fr/hassRenaultZE, pull requests merged in 2021-02, with the labels that each got.

#116 Add documentation about hvac limitation on ZE50
  CONFIGURE.md
  README.md
Labels: documentation

#114 Drop support for Climate entity
  README.md
  custom_components/renault/climate.py
  custom_components/renault/const.py
Labels: breaking

#121 Bump renault-api to v0.1.2
  custom_components/renault/manifest.json
  requirements.txt
Labels: dependencies

#128 Update readme with minimum Home Assistant version
  README.md
Labels: documentation
